### ISSUE TITLE
Allow for nested variables

### ISSUE THREAD

**Issue by hammadj** [relax/relate#14]
Right now, I am unable to make the following request:
```js
function mapQueryToProps(props) {
  return {
    fragments: {
      user: {
        _id: 1,
        name: 1,
        picture: 1,
        bio: 1,
        posts: {
          _id,
          title
        }
      }
    },
    variablesTypes: {
      user: {
        id: 'String!'
        posts: {
          skip: 'Int!',
          limit: 'Int!'
        }
      }
    },
    initialVariables: {
      user: {
        id: props.userId
        posts: {
          skip: 0,
          limit: 10
        }
      }
    }
  };
}

```

AFAIK this is a fairly common use case and NEEDS to be supported :)

**Comment by bruno12mota** [comment]
Hey @hammadj that's true. And should be simple to make it support. Haven't done it yet since I didn't need it for Relax. Will try to make it today 😉

**Comment by hammadj** [comment]
Awesome, looking forward to it! I'm using this in a react native app since its the only graphQL client i found that integrates with redux and works on RN. This one missing feature is my only gripe with it so far!

**Comment by bruno12mota** [comment]
That's great! I'm working on it now ;)

**Comment by bruno12mota** [comment]
Done! Version 0.6.6 now supports nested variables. Let me know if you find any issue 👍
