### ISSUE TITLE
Data masking

### ISSUE THREAD

**Issue by sedubois** [relax/relate#20]
[Data masking](https://facebook.github.io/relay/docs/thinking-in-relay.html#data-masking) (masking a child component's data within its parent) is a quite important feature of Relay, and I wonder if it is provided in Relate?

NB: It is also missing from [Apollo](https://github.com/apollostack/react-apollo/issues/262).

**Comment by bruno12mota** [comment]
Relate does have data masking at a container level 😄 

To have data masking on the presentational components level fragments would have to be declared differently with a decorator as well for example.
