### ISSUE TITLE
Converting null properties into empty objects?

### ISSUE THREAD

**Issue by bs1180** [relax/relate#3]
Thanks for cool library, it's proving very useful so far. I have noticed that null responses are being converted into empty objects - is it intentional? For example, if my query is:
```
query {
  post (id: 123) {
    id
    name
  }
}
```
and there is no post with that ID, my graphql correctly returns:
```
data: {
  post: null
}
```
But relate injects props as {} rather than null, which is unexpected.

**Comment by bruno12mota** [comment]
Got to fix that indeed, well spotted!
