### ISSUE TITLE
Nested fragments don't receive correct data

### ISSUE THREAD

**Issue by bs1180** [relax/relate#6]
I have a component that requests the following data:
```
const fragments = {
  viewer: {
    claims: {
      _id: true,
      name: true,
      status: true
    }
  }
}
```
The data is returned correctly from my server (as observed in the redux devtools):
<img width="449" alt="screen shot 2016-04-17 at 19 25 27" src="https://cloud.githubusercontent.com/assets/5904336/14588792/77b003b6-04d2-11e6-85da-1f8bae60e1b2.png">
However, the component doesn't actually receive the correct data as props, only the node Ids. 
<img width="225" alt="screen shot 2016-04-17 at 19 33 19" src="https://cloud.githubusercontent.com/assets/5904336/14588816/48a1301c-04d3-11e6-9c8f-1179f7b074db.png">
Everything works fine for data requested at the highest level, it's the nested nodes which have problems. 
For now I just use the `id` instead, which doesn't get converted into a node.

**Comment by bruno12mota** [comment]
Strange, think I've covered that in the tests, let me check

**Comment by bruno12mota** [comment]
Seems to be passing the test: https://github.com/relax/relate/commit/17b2f561ccc93e2044c0a0c00a3b835608c86e2a are you using relate version 0.2.3?

**Comment by bs1180** [comment]
@bruno12mota Thanks for being so responsive. Yes, on 0.2.3. Here's the [entire component](https://gist.github.com/bs1180/bd68b017fcba2163b0c5ef2f23381c9a) - at the moment, `id` works (leaving the received data alone) but changing it to `_id` doesn't.

**Comment by bruno12mota** [comment]
For it to be converted to node you must use the _id property yes. According to the test I've made (which follows exactly your example it should work. By the way in:

```js
const data = (
  null,
  null,
  (props) => ({ 
    fragments: {
      viewer: {
        claims: {
          _id: true,
          name: true,
          status: true,
          created_at: true
        }
    }
  } 
 })
)
```

You can remove the two first null values.

```js
const data = (
  (props) => ({ 
    fragments: {
      viewer: {
        claims: {
          _id: true,
          name: true,
          status: true,
          created_at: true
        }
    }
  } 
 })
)
```

Relate will also look for the config in the last parameter. As to the issue, will do some more digging.

**Comment by bruno12mota** [comment]
Oh might have found the issue:

```js
const isId = data && typeof data === 'string' && this.db[data];
````

You're receiving your ids as numbers right?

**Comment by bruno12mota** [comment]
Fixed on https://github.com/relax/relate/commit/939560dd2be6c20ed28bcb195bd00da78383943d

Change to version 0.2.4 and it should work now ;)

**Comment by bs1180** [comment]
Thanks for the fix.

**Comment by bruno12mota** [comment]
No problem, let me know if it's working

**Comment by bs1180** [comment]
Yup, just tried and it's good. Cheers.

**Comment by bruno12mota** [comment]
Nice 😄  cheers!
