### ISSUE TITLE
Q: Refreshing multiple containers

### ISSUE THREAD

**Issue by spatius** [relax/relate#7]
We're using two different containers, ListView and EditView.
Both are visible side by side. ( https://www.dropbox.com/s/z23n2ntychzgbbe/Screenshot%202016-05-06%2016.59.07.png?dl=0 )
ListView uses list query (`{ list(type: String) { ... } }`) and EditView uses edit query (`{ edit(type: String, id: ID) { ... } }`).
EditView also has save mutation (`{ save(type: String, id: ID, [type]) { ... } }`) - [type] is dynamic key - we're using that instead of unions.
So if we were editing user, the mutation query would be `{ save(type: String, id: ID, user) { ... } }`, etc..

The question is how to refresh the list query (and edit query) after save mutation is executed?
Do we need to call `relate.refresh()` on all containers?

.. Also one, somewhat related question..
Is it possible to have nested queries with arguments?
So, instead of `{ list(type: String) { ... } }` we'd like to have `{ client { list(type: String) { ... } } }`. Client is our viewer type (from Relay world). That same class is also a return type for save mutation.

Thank you and take care!
Miran

**Comment by bruno12mota** [comment]
As to your first question. If you retrieve an _id from the save mutation Relate will update every container that is using that node. So you shouldn't have to do nothing as long as your mutation (using relate on a redux action) looks like this:

```js
function save (id, type, value) {
  mutation({
    fragments: {
      save {
        _id: 1
      }
    },
    variables: {
      save: {
        id: {
          value: id,
          type: 'ID!'
        },
        type: {
          value: type,
          type: 'String!'
        },
        value: {
          value: value,
          type: 'String'
        }
      }
    }
  });
}
```

Unfortunately for now it doesn't support nested fragments with queries. That should change soon 😃
