### ISSUE TITLE
Relate bypasses Redux props subscription on nested objects

### ISSUE THREAD

**Issue by s-coimbra21** [relax/relate#8]
When relate updates an object's nested props, redux subscriptions are bypassed.

For example:
ComponentA has props from relate fragments 
`
const objFromGraphqlFragments = { level1: { level2: 99 } }; 
`
If we increment level2 through a mutation or with the result of a new query, Redux will not be able to listen to them, thus, lifecycle callbacks like componentWillReceiveProps or shouldComponentUpdate will not fire correctly.

Instead of firing with the following props:
`this.props.objFromGraphqlFragments: { level1: { level2: 99 } };
nextProps.objFromGraphqlFragments: { level1: { level2: 100 } };`

It only fires when loading is set to false. At that points, this.props and nextProps are most likely equal.

**Comment by bruno12mota** [comment]
Should be fixed now, let me know 👍

**Comment by s-coimbra21** [comment]
Fix introduced another bug where `_id` fields are incorrectly mutated when a mutation happens.
